# Generated by Django 2.2.17 on 2020-12-22 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('D', 'Dance'), ('M', 'Music'), ('P', 'Photography'), ('V', 'Videography'), ('A', 'Art'), ('O', 'Other')], default='N/A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='N/A', max_length=6)),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('skill_set', models.ManyToManyField(to='art.Skillset')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='N/A', max_length=50)),
                ('state', models.CharField(default='N/A', max_length=50)),
                ('city', models.CharField(default='N/A', max_length=50)),
                ('email', models.CharField(default='N/A', max_length=50)),
                ('facebook_link', models.CharField(blank=True, max_length=50)),
                ('instagram_link', models.CharField(blank=True, max_length=50)),
                ('youtube_link', models.CharField(blank=True, max_length=50)),
                ('other_sites', models.CharField(blank=True, max_length=200)),
                ('phone', models.IntegerField()),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
